language: node_js
node_js:
  - "4.0"
script: istanbul cover node_modules/mocha/bin/_mocha
addons:
  code_climate:
    repo_token: CODECLIMATE_TOKEN 
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info

